### ISSUE TITLE
Update aerie-db-migration docs

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie-docs#31]
There are two new arguments in aerie-db-migration, `env-path`, and `network-location` as of [#845](https://github.com/NASA-AMMOS/aerie/pull/845).

**Comment by mattdailis** [comment]
We should also document additional installation requirements

**Comment by Mythicaeda** [comment]
We should document how to install the requirements from the [requirements.txt](https://pip.pypa.io/en/stable/cli/pip_freeze/#examples).
