### ISSUE TITLE
Small Typos on ConOps Page

### ISSUE THREAD

**Issue by Me-ghana** [NASA-AMMOS/aerie-docs#45]
On docs page https://nasa-ammos.github.io/aerie-docs/overview/concept-of-operations/

Whereas, principles of ~~and~~ simulation are embarrassingly similar for activities and commands.

On the other end of the spectrum, a mission can choose to manually [create?] activity plans, basically not utilizing modeling, simulation or scheduling capabilities, while leveraging command expansion to automate sequence generation based on planning inputs.

**Comment by camargo** [comment]
@Me-ghana For future issues, any documentation issues can be added to this repo. Transferred this issue here.

**Comment by camargo** [comment]
Also would love PRs for these small fixes if you have the time!

**Comment by andreamconnell** [comment]
Resolved in https://github.com/NASA-AMMOS/aerie-docs/pull/106
